### ISSUE TITLE
Callbacks have to be on Bridge not Lock level

### ISSUE THREAD

**Issue by Zefau** [Mik13/nuki-bridge-api#10]
Hi Mik13,

sorry for opening an issue again. I'm facing some issue within my implementation with the regards to the callbacks.
Due to this, I was diving a bit deeper into this. 

In your nuki-bridge-api, all callback functions are available on the level of the Nuki's. Though, callbacks are independent of Nuki's and are available on Bridge level (they do not require a Nuki ID). Thus, callbacks do apply for all Nuki's available on a Bridge.

From my understanding of this API implementation though, I need an instance of a Nuki to create / list callbacks.

https://github.com/Mik13/nuki-bridge-api/blob/bc8410d6002c44ed0545e1b3cd152b78061e112b/lib/nuki.js#L118
https://github.com/Mik13/nuki-bridge-api/blob/bc8410d6002c44ed0545e1b3cd152b78061e112b/lib/nuki.js#L143

**Comment by Mik13** [comment]
Sorry for the late response.

Can you check out https://github.com/Mik13/nuki-bridge-api/tree/bridge_callback please? I've implemented (untested) the callback functions via Bridge.

Thank you in advance!

**Comment by Zefau** [comment]
Looks like it works perfect. Thanks!

**Comment by Mik13** [comment]
Perfekt, thanks!

Published version 1.5.0
