### ISSUE TITLE
Allow to apply action on certain Nuki without retrieving all of them from the Bridge

### ISSUE THREAD

**Issue by Zefau** [Mik13/nuki-bridge-api#4]
Hi there,

thanks again for the API implementation.
While using the API I faced the issue that I would like to apply an action on a specific Nuki. Based on the current API implementation, I have to retrieve all the Nuki's from the bridge using `bridge.list().then(..)` and filter out the specific Nuki to apply my action.

I would prefer to get the Nuki via the ID and apply my action, like `bridge.get(NukiId).then(..)` where `NukiId` has been retrieved earlier (or is known already).

Thanks in advanced and kind regards
Zefau

**Comment by Mik13** [comment]
Very good idea!

Added the `get`-function, and with the second parameter you can skip the validation.

Best regards!

**Comment by Zefau** [comment]
Thanks for the quick implementation.
Maybe one question regarding the callback. How come the following code is working, but the `then()` function is not showing anything in the log (though `catch()` is).

`nuki.addCallback(url, port, false, root).then(function(res) {console.log(JSON.stringify(res))}).catch(function(e)
					{JSON.stringify(e)});`

Thanks,
Zefau
