### ISSUE TITLE
Nuki Opener Feature Request

### ISSUE THREAD

**Issue by corincorvus** [Mik13/nuki-bridge-api#40]
Hi,

may it possible to get infos of the opener? For example: If anyone ring the doorbell, the Opener is notified and i can get this trigger to let blinking the Smart Lights?

Only Smart Lock or Bridge i think is not very useful.

Thanks

**Comment by Mik13** [comment]
Hi!

Great idea. I do not have a Operner and I am not actively maintaining this repo, but if you create a pull request I am more than happy to merge it.

Best regards!
