### ISSUE TITLE
[Feature Request] Bridge discovery

### ISSUE THREAD

**Issue by Zefau** [Mik13/nuki-bridge-api#5]
HI there,

could you implement a functionality to discover the bridges based on a request to https://api.nuki.io/discover/bridges ?

Thanks and kind regards,
Zefau

**Comment by Mik13** [comment]
I've created a pull request. Could you please test and tell me if that fits your needs?

Thanks in advance

**Comment by Zefau** [comment]
Thank you very much. You haven't used `https://api.nuki.io/discover/bridges` though, have you? Couldn't find it. 
Have you tested the code? Unfortunately I only have a software bridge and thus no `/auth` or `/configAuth` available. Only the mentioned URL is available for me.

**Comment by Mik13** [comment]
I've used it here: https://github.com/Mik13/nuki-bridge-api/commit/5f9f864a4584c1184941ee01e0e91ded6b168974#diff-c4e94e460a7fbb7e15211d9856d8d855R80

I have tested with my hardware bridge, yes.

**Comment by Zefau** [comment]
With a software bridge https://github.com/Mik13/nuki-bridge-api/blob/master/lib/bridge-discovery.js#L84 does not return an IP or a port. It only contains `bridgeId`.
The result in my case (I have changed `bridgeId` to random number though):
`{"bridges":[{"bridgeId":9151414130,"dateUpdated":"2018-12-28T14:34:23Z"}],"errorCode":0}`

**Comment by Mik13** [comment]
Seems to be a problem with the software bridge, see here: https://developer.nuki.io/t/bridge-discovery-http-api-activation/87/2

Answer 10 might solve your problem.

Without ip and port, we can't send the HTTP-API the requests.
