### ISSUE TITLE
Support for hashed token

### ISSUE THREAD

**Issue by Zefau** [Mik13/nuki-bridge-api#8]
Hi there, it's me again ;-)

The Bridge API received a little update and supports hashed tokens now, see https://developer.nuki.io/page/nuki-bridge-http-api-180/4/#heading--token.

This is only for hardware bridges though, not for software bridge (which I own).

I would appreciate if you / we could implement this in this API.

**Comment by Zefau** [comment]
From my point of view, the `Bridge` constructor must run the `info` function once its instantiated, to know if it a hard- or software bridge.
Once that is done, the `_request` can be refactored to either send a hash token or the normal token.

**Comment by Mik13** [comment]
First of all, thanks you for your input and help!

I've commented the pull request.

**Comment by Mik13** [comment]
Commenting you last comment in the PR:

> I will refactor it in a way, that always a hashed token is send first and when the request fails, a plain token is used instead.

That would be a very good way to handle this.

**Comment by Mik13** [comment]
I think we can close this issue.
